name: tennis-tracker
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - scipy=1.12.0
  - opencv=4.9.*
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - pytorch-cuda=11.8
  - pip:
      - boxmot
      - filterpy==1.4.5
      - json5==0.9.25
      - ultralytics==8.1.29
